{"name": "Click Add to Calendar link", "status": "failed", "statusDetails": {"message": "AssertionError: FAILURE: assert False\ntest_Events.py:355 in test_17() -> with check, allure.step(\"C58500: File is downloaded\"):\ntest_Events.py:356 in test_17 -> assert cond\nAssertionError: assert False\n\n\n------------------------------------------------------------\nFailed Checks: 1\n------------------------------------------------------------\nself = <Tests.test_Events.TestEvents object at 0x7f38d89d5390>\ndriver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"ed39a82c-1e12-4ea5-8d76-313a1d5e0fa4\")>\n\n    @severity(severity_level.CRITICAL)\n    @allure.feature('Individual Events')\n    @allure.title(\"Click Add to Calendar link\")\n    @allure.issue(\"QP-268\", \"Story QP-268\")\n    @allure.issue(\"QP-356\", \"Epic QP-356\")\n    @allure.testcase(\"58500\", \"C58500\")\n    @pytest.mark.dependency(depends=[\"test_8\"])\n    def test_17(self, driver):\n        events_obj = Events(driver)\n        download_dir = self.create_download_dir(self.current_browser)\n        file_name = self.get_download_file_name(driver.current_url)\n        file_path = os.path.join(download_dir, file_name)\n        events_obj.click_single_event_add_to_calendar_link()\n    \n        cond = False\n        for _ in range(10):\n            if os.path.exists(file_path):\n                cond = True\n                break\n            time.sleep(1)\n        with check, allure.step(\"C58500: File is downloaded\"):\n            assert cond\n    \n        file_content = {}\n>       file = open(file_path, 'r')\nE       FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/QUBA_WEB/QUBA_WEB/Resources/firefox_download_dir/leverage-synergies.ics'\n\nTests/test_Events.py:359: FileNotFoundError", "trace": "FAILURE: assert False\ntest_Events.py:355 in test_17() -> with check, allure.step(\"C58500: File is downloaded\"):\ntest_Events.py:356 in test_17 -> assert cond\nAssertionError: assert False\n\n\n------------------------------------------------------------\nFailed Checks: 1\n------------------------------------------------------------\nself = <Tests.test_Events.TestEvents object at 0x7f38d89d5390>\ndriver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"ed39a82c-1e12-4ea5-8d76-313a1d5e0fa4\")>\n\n    @severity(severity_level.CRITICAL)\n    @allure.feature('Individual Events')\n    @allure.title(\"Click Add to Calendar link\")\n    @allure.issue(\"QP-268\", \"Story QP-268\")\n    @allure.issue(\"QP-356\", \"Epic QP-356\")\n    @allure.testcase(\"58500\", \"C58500\")\n    @pytest.mark.dependency(depends=[\"test_8\"])\n    def test_17(self, driver):\n        events_obj = Events(driver)\n        download_dir = self.create_download_dir(self.current_browser)\n        file_name = self.get_download_file_name(driver.current_url)\n        file_path = os.path.join(download_dir, file_name)\n        events_obj.click_single_event_add_to_calendar_link()\n    \n        cond = False\n        for _ in range(10):\n            if os.path.exists(file_path):\n                cond = True\n                break\n            time.sleep(1)\n        with check, allure.step(\"C58500: File is downloaded\"):\n            assert cond\n    \n        file_content = {}\n>       file = open(file_path, 'r')\nE       FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/QUBA_WEB/QUBA_WEB/Resources/firefox_download_dir/leverage-synergies.ics'\n\nTests/test_Events.py:359: FileNotFoundError"}, "steps": [{"name": "C58500: File is downloaded", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n", "trace": "  File \"/home/runner/work/QUBA_WEB/QUBA_WEB/Tests/test_Events.py\", line 356, in test_17\n    assert cond\n"}, "start": 1733302683834, "stop": 1733302683834}], "parameters": [{"name": "driver", "value": "'firefox'"}], "start": 1733302673599, "stop": 1733302683866, "uuid": "0d333a8e-9dc4-4d80-8c23-20dc21be73b2", "historyId": "9c2530e10a0046f38af59847b347483e", "testCaseId": "e07010f572494ae9108f05899b49d9e7", "fullName": "Tests.test_Events.TestEvents#test_17", "labels": [{"name": "severity", "value": "critical"}, {"name": "feature", "value": "Individual Events"}, {"name": "tag", "value": "dependency(depends=['test_8'])"}, {"name": "tag", "value": "flaky(reruns=3, reruns_delay=1)"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_Events"}, {"name": "subSuite", "value": "TestEvents"}, {"name": "host", "value": "fv-az1773-789"}, {"name": "thread", "value": "1857-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_Events"}], "links": [{"type": "tms", "url": "https://hedgehoglabqa.testrail.io/index.php?/cases/view/58500", "name": "C58500"}, {"type": "issue", "url": "https://hedgehog-lab.atlassian.net/browse/QP-356", "name": "Epic QP-356"}, {"type": "issue", "url": "https://hedgehog-lab.atlassian.net/browse/QP-268", "name": "Story QP-268"}]}