{"uuid": "4aadf606-5f0a-4259-aeb5-4889e2670336", "children": ["7922f14f-c848-4311-8faf-118bb33dc642"], "befores": [{"name": "proxy_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created\nfrom unknown error: cannot find msedge binary\nStacktrace:\n0   msedgedriver                        0x00000001047bb228 msedgedriver + 6914600\n1   msedgedriver                        0x00000001047b329a msedgedriver + 6881946\n2   msedgedriver                        0x000000010417967c msedgedriver + 353916\n3   msedgedriver                        0x00000001041a9d89 msedgedriver + 552329\n4   msedgedriver                        0x00000001041a5590 msedgedriver + 533904\n5   msedgedriver                        0x00000001041e84b3 msedgedriver + 808115\n6   msedgedriver                        0x00000001041e793f msedgedriver + 805183\n7   msedgedriver                        0x00000001041dd983 msedgedriver + 764291\n8   msedgedriver                        0x00000001041b185b msedgedriver + 583771\n9   msedgedriver                        0x00000001041b21ae msedgedriver + 586158\n10  msedgedriver                        0x000000010477eed2 msedgedriver + 6667986\n11  msedgedriver                        0x00000001047831af msedgedriver + 6685103\n12  msedgedriver                        0x000000010475e6f9 msedgedriver + 6534905\n13  msedgedriver                        0x00000001047839a1 msedgedriver + 6687137\n14  msedgedriver                        0x000000010474e433 msedgedriver + 6468659\n15  msedgedriver                        0x00000001047a1c08 msedgedriver + 6810632\n16  msedgedriver                        0x00000001047a1d73 msedgedriver + 6810995\n17  msedgedriver                        0x00000001047b2e5a msedgedriver + 6880858\n18  libsystem_pthread.dylib             0x00007ff802cc018b _pthread_start + 99\n19  libsystem_pthread.dylib             0x00007ff802cbbae3 thread_start + 15\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pluggy/_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pluggy/_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/fixtures.py\", line 906, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/runner/work/QUBA_WEB/QUBA_WEB/Common/BaseClass.py\", line 148, in proxy_driver\n    proxy_driver = webdriver.Edge(service=EdgeService(EdgeChromiumDriverManager().install()), options=options)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/edge/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py\", line 61, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 208, in __init__\n    self.start_session(capabilities)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 292, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1731480649254, "stop": 1731480654837}], "start": 1731480649254, "stop": 1731480654886}