{"uid":"8bf2f0eede532148","name":"Click Add to Calendar link","fullName":"Tests.test_Events.TestEvents#test_17","historyId":"cd1918ad72dc99a98ac7ead403f34017","time":{"start":1733302653586,"stop":1733302664391,"duration":10805},"status":"failed","statusMessage":"AssertionError: FAILURE: assert False\ntest_Events.py:355 in test_17() -> with check, allure.step(\"C58500: File is downloaded\"):\ntest_Events.py:356 in test_17 -> assert cond\nAssertionError: assert False\n\n\n------------------------------------------------------------\nFailed Checks: 1\n------------------------------------------------------------\nself = <Tests.test_Events.TestEvents object at 0x105eb8650>\ndriver = <selenium.webdriver.safari.webdriver.WebDriver (session=\"6DF4DBA8-63BD-4037-A183-35F1F2588A0F\")>\n\n    @severity(severity_level.CRITICAL)\n    @allure.feature('Individual Events')\n    @allure.title(\"Click Add to Calendar link\")\n    @allure.issue(\"QP-268\", \"Story QP-268\")\n    @allure.issue(\"QP-356\", \"Epic QP-356\")\n    @allure.testcase(\"58500\", \"C58500\")\n    @pytest.mark.dependency(depends=[\"test_8\"])\n    def test_17(self, driver):\n        events_obj = Events(driver)\n        download_dir = self.create_download_dir(self.current_browser)\n        file_name = self.get_download_file_name(driver.current_url)\n        file_path = os.path.join(download_dir, file_name)\n        events_obj.click_single_event_add_to_calendar_link()\n    \n        cond = False\n        for _ in range(10):\n            if os.path.exists(file_path):\n                cond = True\n                break\n            time.sleep(1)\n        with check, allure.step(\"C58500: File is downloaded\"):\n            assert cond\n    \n        file_content = {}\n>       file = open(file_path, 'r')\nE       FileNotFoundError: [Errno 2] No such file or directory: '/Users/runner/Downloads/leverage-synergies.ics'\n\nTests/test_Events.py:359: FileNotFoundError","statusTrace":"FAILURE: assert False\ntest_Events.py:355 in test_17() -> with check, allure.step(\"C58500: File is downloaded\"):\ntest_Events.py:356 in test_17 -> assert cond\nAssertionError: assert False\n\n\n------------------------------------------------------------\nFailed Checks: 1\n------------------------------------------------------------\nself = <Tests.test_Events.TestEvents object at 0x105eb8650>\ndriver = <selenium.webdriver.safari.webdriver.WebDriver (session=\"6DF4DBA8-63BD-4037-A183-35F1F2588A0F\")>\n\n    @severity(severity_level.CRITICAL)\n    @allure.feature('Individual Events')\n    @allure.title(\"Click Add to Calendar link\")\n    @allure.issue(\"QP-268\", \"Story QP-268\")\n    @allure.issue(\"QP-356\", \"Epic QP-356\")\n    @allure.testcase(\"58500\", \"C58500\")\n    @pytest.mark.dependency(depends=[\"test_8\"])\n    def test_17(self, driver):\n        events_obj = Events(driver)\n        download_dir = self.create_download_dir(self.current_browser)\n        file_name = self.get_download_file_name(driver.current_url)\n        file_path = os.path.join(download_dir, file_name)\n        events_obj.click_single_event_add_to_calendar_link()\n    \n        cond = False\n        for _ in range(10):\n            if os.path.exists(file_path):\n                cond = True\n                break\n            time.sleep(1)\n        with check, allure.step(\"C58500: File is downloaded\"):\n            assert cond\n    \n        file_content = {}\n>       file = open(file_path, 'r')\nE       FileNotFoundError: [Errno 2] No such file or directory: '/Users/runner/Downloads/leverage-synergies.ics'\n\nTests/test_Events.py:359: FileNotFoundError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1733302618062,"stop":1733302618110,"duration":48},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"driver","time":{"start":1733302618110,"stop":1733302623789,"duration":5679},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"failed","statusMessage":"AssertionError: FAILURE: assert False\ntest_Events.py:355 in test_17() -> with check, allure.step(\"C58500: File is downloaded\"):\ntest_Events.py:356 in test_17 -> assert cond\nAssertionError: assert False\n\n\n------------------------------------------------------------\nFailed Checks: 1\n------------------------------------------------------------\nself = <Tests.test_Events.TestEvents object at 0x105eb8650>\ndriver = <selenium.webdriver.safari.webdriver.WebDriver (session=\"6DF4DBA8-63BD-4037-A183-35F1F2588A0F\")>\n\n    @severity(severity_level.CRITICAL)\n    @allure.feature('Individual Events')\n    @allure.title(\"Click Add to Calendar link\")\n    @allure.issue(\"QP-268\", \"Story QP-268\")\n    @allure.issue(\"QP-356\", \"Epic QP-356\")\n    @allure.testcase(\"58500\", \"C58500\")\n    @pytest.mark.dependency(depends=[\"test_8\"])\n    def test_17(self, driver):\n        events_obj = Events(driver)\n        download_dir = self.create_download_dir(self.current_browser)\n        file_name = self.get_download_file_name(driver.current_url)\n        file_path = os.path.join(download_dir, file_name)\n        events_obj.click_single_event_add_to_calendar_link()\n    \n        cond = False\n        for _ in range(10):\n            if os.path.exists(file_path):\n                cond = True\n                break\n            time.sleep(1)\n        with check, allure.step(\"C58500: File is downloaded\"):\n            assert cond\n    \n        file_content = {}\n>       file = open(file_path, 'r')\nE       FileNotFoundError: [Errno 2] No such file or directory: '/Users/runner/Downloads/leverage-synergies.ics'\n\nTests/test_Events.py:359: FileNotFoundError","statusTrace":"FAILURE: assert False\ntest_Events.py:355 in test_17() -> with check, allure.step(\"C58500: File is downloaded\"):\ntest_Events.py:356 in test_17 -> assert cond\nAssertionError: assert False\n\n\n------------------------------------------------------------\nFailed Checks: 1\n------------------------------------------------------------\nself = <Tests.test_Events.TestEvents object at 0x105eb8650>\ndriver = <selenium.webdriver.safari.webdriver.WebDriver (session=\"6DF4DBA8-63BD-4037-A183-35F1F2588A0F\")>\n\n    @severity(severity_level.CRITICAL)\n    @allure.feature('Individual Events')\n    @allure.title(\"Click Add to Calendar link\")\n    @allure.issue(\"QP-268\", \"Story QP-268\")\n    @allure.issue(\"QP-356\", \"Epic QP-356\")\n    @allure.testcase(\"58500\", \"C58500\")\n    @pytest.mark.dependency(depends=[\"test_8\"])\n    def test_17(self, driver):\n        events_obj = Events(driver)\n        download_dir = self.create_download_dir(self.current_browser)\n        file_name = self.get_download_file_name(driver.current_url)\n        file_path = os.path.join(download_dir, file_name)\n        events_obj.click_single_event_add_to_calendar_link()\n    \n        cond = False\n        for _ in range(10):\n            if os.path.exists(file_path):\n                cond = True\n                break\n            time.sleep(1)\n        with check, allure.step(\"C58500: File is downloaded\"):\n            assert cond\n    \n        file_content = {}\n>       file = open(file_path, 'r')\nE       FileNotFoundError: [Errno 2] No such file or directory: '/Users/runner/Downloads/leverage-synergies.ics'\n\nTests/test_Events.py:359: FileNotFoundError","steps":[{"name":"C58500: File is downloaded","time":{"start":1733302664317,"stop":1733302664318,"duration":1},"status":"failed","statusMessage":"AssertionError: assert False\n","statusTrace":"  File \"/Users/runner/work/QUBA_WEB/QUBA_WEB/Tests/test_Events.py\", line 356, in test_17\n    assert cond\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":true,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"stepsCount":1,"shouldDisplayMessage":true,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"driver::0","time":{"start":1733302678653,"stop":1733302678884,"duration":231},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"severity","value":"critical"},{"name":"feature","value":"Individual Events"},{"name":"tag","value":"dependency(depends=['test_8'])"},{"name":"tag","value":"flaky(reruns=3, reruns_delay=1)"},{"name":"parentSuite","value":"Tests"},{"name":"suite","value":"test_Events"},{"name":"subSuite","value":"TestEvents"},{"name":"host","value":"Mac-1733301632318.local"},{"name":"thread","value":"2209-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"Tests.test_Events"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"driver","value":"'safari'"}],"links":[{"name":"C58500","url":"https://hedgehoglabqa.testrail.io/index.php?/cases/view/58500","type":"tms"},{"name":"Epic QP-356","url":"https://hedgehog-lab.atlassian.net/browse/QP-356","type":"issue"},{"name":"Story QP-268","url":"https://hedgehog-lab.atlassian.net/browse/QP-268","type":"issue"}],"hidden":true,"retry":true,"extra":{"categories":[],"tags":["dependency(depends=['test_8'])","flaky(reruns=3, reruns_delay=1)"]},"source":"8bf2f0eede532148.json","parameterValues":["'safari'"]}